name: multi_long_press_gesture_recognizer
description: Flutter package for detecting multi-long-press gestures. Supports slop tolerances and a configurable duration.
version: 0.0.1+2
repository: "https://github.com/Bungeefan/multi_long_press_gesture_recognizer"
topics:
  - gesture

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  meta: ^1.15.0
  fake_async: ^1.3.1
